[metadata]
creation_date = "2021/07/19"
maturity = "production"
updated_date = "2022/02/07"

[rule]
author = ["Elastic", "Austin Songer"]
description = """
Identifies the use of the Win32_ShadowCopy class and related cmdlets to achieve shadow copy deletion. This commonly occurs
in tandem with ransomware or other destructive attacks.
"""
from = "now-9m"
index = ["winlogbeat-*", "logs-endpoint.events.*", "logs-windows.*"]
language = "eql"
license = "Elastic License v2"
name = "Volume Shadow Copy Deletion via PowerShell"
note = """## Triage and analysis.

### Investigating Volume Shadow Copy Deletion via WMIC

The Volume Shadow Copy Service (VSS) is a Windows feature that enables system administrators to take snapshots of volumes
that can be later restored or mounted to recover specific files or folders.

A typical step in the playbooks of attackers that have the goal of deploying Ransomware is to delete Volume Shadow Copies
to inhibit any chance of restoring the data without paying the ransom, making any action that deletes shadow copies worth
monitoring.

This rule monitors the execution of PowerShell cmdlets to interact with the Win32_ShadowCopy WMI class, retrieve shadow
copy objects and delete them.

#### Possible investigation steps:

- Identify the user that performed the action and confirm whether or not the user should perform this kind of activity
- Contact the user and confirm if he is aware of this activity
- In case of resize operation, check if the resize value is equal to suspicious values like 401MB
- Investigate other alerts related to the user/host in the last 48 hours.

### False Positive Analysis

- This rule has chances of producing B-TPs (Benign True Positives). If this activity is expected and noisy in your environment,
consider working with Exceptions, preferably using a user and command line combination.

### Related Rules

- Volume Shadow Copy Deleted or Resized via VssAdmin - b5ea4bfe-a1b2-421f-9d47-22a75a6f2921
- Volume Shadow Copy Deletion via WMIC - dc9c1f74-dac3-48e3-b47f-eb79db358f57

### Response and Remediation

- Immediate response should be taken to validate, investigate, and potentially contain the activity to prevent further
post-compromise behavior.
- If triage indicates this activity is Suspicious, immediately start the Incident Response. If this activity was identified
in Domain Controllers or vital servers, consider the whole Domain compromised.
"""
references = [
    "https://docs.microsoft.com/en-us/previous-versions/windows/desktop/vsswmi/win32-shadowcopy",
    "https://powershell.one/wmi/root/cimv2/win32_shadowcopy",
    "https://www.fortinet.com/blog/threat-research/stomping-shadow-copies-a-second-look-into-deletion-methods",
]
risk_score = 73
rule_id = "d99a037b-c8e2-47a5-97b9-170d076827c4"
severity = "high"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Impact"]
timestamp_override = "event.ingested"
type = "eql"

query = '''
process where event.type in ("start", "process_started") and
  process.name : ("powershell.exe", "pwsh.exe", "powershell_ise.exe") and 
  process.args : ("*Get-WmiObject*", "*gwmi*", "*Get-CimInstance*", "*gcim*") and
  process.args : ("*Win32_ShadowCopy*") and
  process.args : ("*.Delete()*", "*Remove-WmiObject*", "*rwmi*", "*Remove-CimInstance*", "*rcim*")
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1490"
reference = "https://attack.mitre.org/techniques/T1490/"
name = "Inhibit System Recovery"



[rule.threat.tactic]
id = "TA0040"
reference = "https://attack.mitre.org/tactics/TA0040/"
name = "Impact"

