[metadata]
creation_date = "2020/02/18"
maturity = "production"
updated_date = "2022/02/07"

[rule]
author = ["Elastic"]
description = """
Identifies use of vssadmin.exe for shadow copy deletion or resizing on endpoints. This commonly occurs in tandem with
ransomware or other destructive attacks.
"""
from = "now-9m"
index = ["winlogbeat-*", "logs-endpoint.events.*", "logs-windows.*"]
language = "eql"
license = "Elastic License v2"
name = "Volume Shadow Copy Deleted or Resized via VssAdmin"
note = """## Triage and analysis

### Investigating Volume Shadow Copy Deleted or Resized via VssAdmin

The Volume Shadow Copy Service (VSS) is a Windows feature that enables system administrators to take snapshots of volumes
that can be later restored or mounted to recover specific files or folders.

A typical step in the playbooks of attackers that have the goal of deploying Ransomware is to delete Volume Shadow Copies
to inhibit any chance of restoring the data without paying the ransom, making any action that deletes shadow copies worth
monitoring.

This rule monitors the execution of Vssadmin.exe to either delete or resize shadow copies.

#### Possible investigation steps:

- Identify the user that performed the action and confirm whether or not the user should perform this kind of activity
- Contact the user and confirm if he is aware of this activity
- In case of resize operation, check if the resize value is equal to suspicious values like 401MB
- Investigate other alerts related to the user/host in the last 48 hours.

### False Positive Analysis

- This rule has chances of producing B-TPs (Benign True Positives). If this activity is expected and noisy in your environment,
consider working with Exceptions, preferably using a user and command line combination.

### Related Rules

- Volume Shadow Copy Deletion via WMIC - dc9c1f74-dac3-48e3-b47f-eb79db358f57
- Volume Shadow Copy Deletion via PowerShell - d99a037b-c8e2-47a5-97b9-170d076827c4

### Response and Remediation

- Immediate response should be taken to validate, investigate, and potentially contain the activity to prevent further
post-compromise behavior.
- If triage indicates this activity is Suspicious, immediately start the Incident Response. If this activity was identified
in Domain Controllers or vital servers, consider the whole Domain compromised.
"""
risk_score = 73
rule_id = "b5ea4bfe-a1b2-421f-9d47-22a75a6f2921"
severity = "high"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Impact"]
timestamp_override = "event.ingested"
type = "eql"

query = '''
process where event.type in ("start", "process_started") and event.action == "start" 
  and (process.name : "vssadmin.exe" or process.pe.original_file_name == "VSSADMIN.EXE") and
  process.args in ("delete", "resize") and process.args : "shadows*"
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
reference = "https://attack.mitre.org/techniques/T1490/"
name = "Inhibit System Recovery"
id = "T1490"


[rule.threat.tactic]
reference = "https://attack.mitre.org/tactics/TA0040/"
name = "Impact"
id = "TA0040"

